spring:
  application:
    name: basket-service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

logging:
  level:
    com.example.basketservice: DEBUG